### ISSUE TITLE
Exception when reading specific StringList file

### ISSUE THREAD

**Issue by tehmufifnman** [Enigma32/Enigma.D3#22]
Diablo 3 Build #46568
The file in question is StringList\Conv_Fol_TP_FesteringWoods.stl

`SNOHelper.LoadFile<StringList>(@"D:\DiabloFiles_46568\StringList\Conv_Fol_TP_FesteringWoods.stl");`

The above throws the below error.

```
   at Enigma.Memory.MemoryReader.Read[T](MemoryAddress address) in D:\projects\Enigma.D3\Enigma.Memory\MemoryReaderImplementations\MemoryReader.cs:line 79
   at Enigma.Memory.MemoryObject.Read[T](Int32 offset) in D:\projects\Enigma.D3\Enigma.Memory\MemoryObject.cs:line 39
   at Enigma.D3.Assets.SNOFile`1.get_Header() in D:\projects\Enigma.D3\Enigma.D3.Assets\SNOFile.cs:line 12
   at Enigma.D3.Assets.SNOHelper.LoadFile[T](String path) in D:\projects\Enigma.D3\Enigma.D3.Assets\SNOHelper.cs:line 17
   at DiabloFileParser.Program.LoadStringLists() in D:\projects\DiabloFileParser\Program.cs:line 46
```

**Comment by Enigma32** [comment]
It works fine for me (enUS locale). Perhaps you've got a bad extraction?

**Comment by tehmufifnman** [comment]
You are absolutely right!  I randomly had a 0kb file for some unknown reason.

Thanks!
